### ISSUE TITLE
ability to mount existing dbs from host

### ISSUE THREAD

**Issue by svnlto** [orlandohohmeier/docker-local-npm#1]
I have `local-npm` running on my host machine and would like to share the `$HOME/.local-npm` folder with this image. If I mount the above into `/data` you image still keeps syncing from skimdb instead. 

Any pointers?

**Comment by orlandohohmeier** [comment]
@svnlto, please excuse my very late response, I somehow missed your request. 

Could you please check the running container (`docker inspect`) to make sure that everything is properly mounted?

Thanks!
