### ISSUE TITLE
local-npm not starting

### ISSUE THREAD

**Issue by MichaelRuhwedel** [orlandohohmeier/docker-local-npm#3]
Hi Orlando,
thanks for the image, it had been working great till recently. We've been getting the following error:
`TypeError: requestsById[request.id].push is not a function
    at /local-npm/node_modules/pouchdb/lib/index.js:247:32
`
In case you find the time to fix it, could you please tag a working version?

Best,
Michael

**Comment by orlandohohmeier** [comment]
Hi @MichaelRuhwedel! This seems to be an issue with `local-npm` itself and is tracked in   https://github.com/nolanlawson/local-npm/issues/131
